name: automacao-backbone

include:
  - Chatwoot/compose.yaml
  - evolution/compose.yaml
  - n8n/compose.yaml
  - minio/compose.yaml

services:
  # Services are now managed in their respective subdirectories

networks:
  backbone_internal:
    name: backbone_backbone_internal
    external: true
